server:
  port: ${SERVER_PORT:8090}


spring:
  datasource:
    url: jdbc:h2:file:${DATA_BASE_PATH:./our-discord-music-bot-h2-db}
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false

application:
  bot:
    token: ${BOT_TOKEN:}